import logging

from fastapi import APIRouter, HTTPException, Request
from llm.client import ask
from rag.index import retrieve_context
from schemas.chat import ChatRequest, ChatResponse

logger = logging.getLogger("roadvision")

router = APIRouter()


@router.post("/chat")
def chat(payload: ChatRequest, request: Request) -> ChatResponse:
    """
    Handles chat messages by processing the input payload and returning a
    response. This function communicates with a language model to generate
    a meaningful reply based on the message history provided in the payload.

    :param payload: The request body containing the chat history. It includes
        all messages as objects that can be serialized for processing.
    :type payload: ChatRequest
    :param request: The incoming FastAPI request, used to access the shared
        ChromaDB client stored on app.state.
    :type request: Request
    :return: A structured response containing the answer generated by the
        language model based on the input messages.
    :rtype: ChatResponse
    :raises HTTPException: If the language model request fails, this exception
        is raised with a 502 status code and corresponding error detail.
    """
    history = [m.model_dump() for m in payload.messages]

    context = []
    if history:
        last_user_message = history[-1]["content"]
        try:
            context = retrieve_context(request.app.state.chroma_client, last_user_message)
        except Exception:
            logger.exception("RAG retrieval failed, continuing without context")

    try:
        answer = ask(history, context=context)
    except Exception as err:
        logger.exception("LLM request failed")
        raise HTTPException(status_code=502, detail="LLM request failed") from err
    return ChatResponse(answer=answer)
